{% set name = "pygnssutils" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygnssutils-{{ version }}.tar.gz
  sha256: 48539d96169eadab60ad2752b7912cde3996d480ffb298ba556652c3500d18d9
build:
  entry_points:
    - gnssstreamer = pygnssutils.gnssstreamer_cli:main
    - gnssserver = pygnssutils.gnssserver_cli:main
    - gnssntripclient = pygnssutils.gnssntripclient_cli:main
    - pyrinexconv = pygnssutils.rinex_conv_cli:main

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=2026.0.0
    - pynmeagps >=1.1.7
    - pyqgc >=1.0.0
    - pyrtcm >=1.2.0
    - pysbf2 >=1.0.4
    - pyserial >=3.5
    - pyspartn >=1.1.0
    - pyubx2 >=1.3.7
    - pyubxutils >=1.0.6
    - pyunigps >=1.0.0

test:
  imports:
    - pygnssutils
  commands:
    - pip check
    - gnssstreamer --help
    - gnssserver --help
    - gnssntripclient --help
    - pyrinexconv --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/semuconsulting/pygnssutils
  description: Python GNSS CLI utility library.
  summary: Python GNSS CLI utility library.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pygnssutils
  dev_url: https://github.com/semuconsulting/pygnssutils

extra:
  recipe-maintainers:
    - semuadmin
